services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://lucaspino07:61D7wZSFfz3NeWR7@cluster0.bisbkqy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
